apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: {{ .Values.configMap.name }}
            mountPath: {{ .Values.volumeMs.container.mountPath }}
          - name: applog
            mountPath: /logs
        ports:
          - name: {{ .Values.service.name }}
            containerPort: {{ .Values.service.targetPort }}
            protocol: {{ .Values.service.protocol }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.env }}
        env:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- toYaml .Values.commonEnv | nindent 10 }}
      - name: {{ .Values.logging.fluentBit.name }}
        image: {{ .Values.logging.fluentBit.image }}:{{ .Values.logging.fluentBit.imageVersion }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: {{ .Values.logging.fluentBit.resources.limits.memory | quote }}
            cpu: {{ .Values.logging.fluentBit.resources.limits.cpu | quote }}
          requests:
            memory: {{ .Values.logging.fluentBit.resources.requests.memory | quote }}
            cpu: {{ .Values.logging.fluentBit.resources.requests.cpu | quote }}
        env:
        - name: LOGSTASH_PREFIX
          value: "{{ .Values.logging.fluentBit.logStashPrefix }}"
        - name: ELASTICSEARCH_HOST
          value: "{{ .Values.logging.fluentBit.elasticSearchHost }}"
        - name: ELASTICSEARCH_PORT
          value: "{{ .Values.logging.fluentBit.elasticSearchPort }}"
        - name: ENV
          value: "{{ .Values.logging.fluentBit.env }}"
        ports:
          - containerPort: {{ .Values.logging.fluentBit.ports.containerPort }}
        volumeMounts:
          - name: applog
            mountPath: /var/log
          - name: fluent-bit-config
            mountPath: /fluent-bit/etc/
      volumes:
        - name: {{ .Values.configMap.name }}
          configMap:
            name: {{ .Values.configMap.name }}
        - name: applog
          emptyDir: {}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config