apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: casestudy
spec:
 containers:
 - name: nginx
   image: nginx:1.14.2
   resources:
     limits:
       memory: 100Mi
       cpu: 100m
     requests:
       cpu: 100m
       memory: 100Mi
   ports:
   - containerPort: 80
   volumeMounts:
   - name: applog
     mountPath: /logs
 - name: flb
   image: fluent/fluent-bit:0.14.2
   resources:
     limits:
       memory: 100Mi
       cpu: 100m
     requests:
       cpu: 100m
       memory: 100Mi
   env:
     - name: LOGSTASH_PREFIX
       value: "migros-"
     - name: ELASTICSEARCH_HOST
       value: "elasticsearch-master-headless"
     - name: ELASTICSEARCH_PORT
       value: "9200"
     - name: ENV
       value: "casestudy"

   ports:
     - containerPort: 2020

   volumeMounts:
     - name: applog
       mountPath: /var/log
     - name: fluentbit-config
       mountPath: /fluent-bit/etc/

 volumes:
   - name: applog
     emptyDir: {}
     # hostPath:
     #   path: /var/log
   - name: varlibdockercontainers
     hostPath:
       path: /var/lib/docker/containers
   - name: fluentbit-config
     configMap:
       name: fluentbit-config
    