name: casestudy
containerName: casestudy-app

replicaCount: 1

logging:
  fluentBit:
    name: fluent-bit
    image: fluent/fluent-bit
    imageVersion: latest
    resources:
      limits:
        memory: "50Mi"
        cpu: "200m"
      requests:
        memory: "50Mi"
        cpu: "100m"
    logStashPrefix: "casestudy"
    elasticSearchHost: "elasticsearch-master-headless"
    elasticSearchPort: "9200"
    ports:
      containerPort: 2020