apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: casestudy
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE filter.conf
  input.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/*.log
        Parser            json
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     15MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${ELASTICSEARCH_HOST}
        Port            ${ELASTICSEARCH_PORT}
        Logstash_Format on
        Type  flb_type
        Logstash_Prefix  ${LOGSTASH_PREFIX}
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key ts
        Time_Format %Y-%m-%dT%H:%M:%S.%L+00:00
        Time_Keep   On
  filter.conf: |
    [FILTER]
        Name modify
        Match *
        Add  env ${ENV}
  