---
clusterName: "elasticsearch"
nodeGroup: "master"

roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"

# HighAvailablity için replicas sayısı arttırılabilir
replicas: 1
minimumMasterNodes: 1


esConfig: 
 elasticsearch.yml: |
   http.cors.enabled: true
   http.cors.allow-origin: "*"


#image: ""
imageTag: "7.10.2"
imagePullPolicy: "IfNotPresent"


esJavaOpts: "-Xmx1g -Xms1g"

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 1Gi

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi

protocol: http
httpPort: 9200
transportPort: 9300

sysctlInitContainer:
  enabled: true