---
# Elastic host ve port ayarı
elasticsearchHosts: "http://elasticsearch-master-headless:9200"

replicas: 1

# image detayı
#image: ""
imageTag: "7.10.2"
imagePullPolicy: "IfNotPresent"

resources:
  requests:
    cpu: "256m"
    memory: "256Mi"
  limits:
    cpu: "512m"
    memory: "750Mi"

protocol: http

serverHost: "0.0.0.0"

healthCheckPath: "/kibana/app/kibana"

# Ingress e ile path base bağlanabilmek için /kibana bu basepath ayarının yapılması gerekiyor
kibanaConfig: 
   kibana.yml: |
      server.basePath: /kibana
      server.rewriteBasePath: true

#ingress ayarları
ingress:
  enabled: true
  
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dev.casestudy.com
      paths:
        - path: /kibana

